### PR TITLE
CNKT-290: Sms Callback and tracking changes 

### PR DESCRIPTION
**Pull request by ayush03agarwal**

### CODE REVIEW

**Comment by kingster** [comment]
Please share example payloads which you would be storing/expecting in respective fields. Without that this change-set is hard to understand. I don't understand why you need a cargo field in the reponse itself.

**Comment by ayush03agarwal** [comment]
For example , Gupshup gives us details if invalid number. To store "details" we are using cargo

{
    "response": {
        "id": "3209270450267955317",
        "phone": "",
        "details": "",
        "status": "success"
    },
    "data": {
        "response_messages": [
            {
                "id": "3209270450267955317-106008291904106642",
                "phone": "917760947385",
                "details": "",
                "status": "success"
            },
            {
                "id": "105",
                "phone": "aldj",
                "details": "The phone number \"aldj\" is not a valid phone number.",
                "status": "error"
            }
        ]
    }
}

**Comment by kingster** [comment]
Not necessarily that all providers are going to provide reponse in a json-object format. What about providers which may respond in xml/plain-text format?

**Comment by ayush03agarwal** [comment]
I am not passing the value of cargo as json. It's key value pair which am converting to json string in ResponseHandler.

**Comment by kingster** [comment]
I am reffering to the scenario where it is not a key value pair, but say
the http response is a xml document.

Thanks
Kinshuk

**Comment by ayush03agarwal** [comment]
As cargo is coming from stencil, I think we can convert any format to key value pair.

**Comment by kingster** [comment]
I wouldn't attempt so. Cargo by definition is free form, and we are
adhering to it in the same way, I wouldn't want to have specific scenarios
where a plain string needs mandatory to be converted into k-v pair.

**Comment by ayush03agarwal** [comment]
(r.cargo.asScala ++ ProviderMeta(r.providerMessageId, requestTracker.provider, smsResponse.message).asMap).getJson)
Initially it was not proper because it was string.

**Comment by kingster** [comment]
IMO I would avoid trying to join cargo with meta without any cause. Instead
the meta and cargo should be handled case by case basis.

Thanks
Kinshuk

**Comment by ayush03agarwal** [comment]
Shall I make cargo and meta as separate fields

**Pull request merged**
